version: '3.8'
services:
  backend:
    build:
      dockerfile: Dockerfile
    container_name: webte_backend
    restart: always
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webte_zaverecne
      MYSQL_USER: webte
      MYSQL_PASSWORD: pass123
    volumes:
      - ./data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
