#version: '3.8'
#services:
#  backend:
#    build:
#      dockerfile: Dockerfile
#    container_name: webte_backend
#    restart: always
#    volumes:
#      - .:/var/www/html
#      - ./php.ini:/usr/local/etc/php/php.ini
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db
#  db:
#    image: mysql:latest
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: webte_zaverecne
#      MYSQL_USER: webte
#      MYSQL_PASSWORD: pass123
#    volumes:
#      - ./data:/var/lib/mysql
#      - ./initdb:/docker-entrypoint-initdb.d
#    ports:
#      - "3306:3306"
version: "3.8"
services:
    app:
        container_name: webte_app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        expose:
            - 9000
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - db
        networks:
            - app_network

    nginx:
#        container_name: webte_app
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - 8001:80
        depends_on:
            - app
        environment:
            NGINX_FPM_HOST: app
            NGINX_ROOT: /usr/src/app/public
        networks:
            - app_network

    db:
#        container_name: webte_app
        image: mysql:8.0.20
        restart: always
        volumes:
            - ./storage/db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
              MYSQL_ROOT_PASSWORD: root
              MYSQL_DATABASE: webte_zaverecne
              MYSQL_USER: webte
              MYSQL_PASSWORD: pass123
        networks:
            - app_network

    redis:
#        container_name: webte_app
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
